name: CI/CD Pipeline

on:
  push:
    branches: [ "feature-1" ]
  pull_request:
    branches: [ "feature-1" ]

jobs:
  build:
    runs-on: kedhar #self

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: SanjanaKrishna/weather-app
          ref: feature-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Run Docker Container
        run: |
          docker compose up -d

      - name: Sleep for 120 seconds
        run: sleep 120s
        shell: bash   

      - name: Clean up
        if: always()
        run: |
          docker compose down
