name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: SanjanaKrishna/weather-app
          ref: feature-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Run Docker Container
        run: |
          docker compose up -d
          
      - name: Get Runner Public IP
        uses: haythem/get-runner-public-ip-address@main
        id: get_ip

          - name: Print IP Addresses
            run: |
              echo "IPv4: ${{ steps.get_ip.outputs.ipv4 }}"
              echo "IPv6: ${{ steps.get_ip.outputs.ipv6 }}"    

      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash   
